#!/bin/bash
PATH=./node_modules/.bin:$PATH

function install-dev {
    python3.9 -m venv .env
    source .env/bin/activate
    pip install -r requirements-dev.txt
    pre-commit install
}

function freeze {
    pip freeze > requirements-dev.txt
}

function clean-env {
    rm -rf .env
}

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-default}
